// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonial from '@/components/sections/about/AboutTestimonial';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTestimonial
          tag="Our Story"
          quote="For those like me who love exotic cuisine, this Indian market is a godsend. Small, yet packed with every authentic essential you need."
          author="Ombretta Corradi"
          role="Local Guide"
          imageSrc="http://img.b2bpic.net/free-photo/condensed-nut-dessert-sprinkled-with-powdered-sugar_140725-6600.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
