// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Visit Us"
          text="Come visit our market in San Secondo Parmense today for fresh, authentic ingredients."
          primaryButton={{
            text: "Call Now",        href: "tel:+393512617506"}}
          secondaryButton={{
            text: "Get Directions",        href: "https://maps.google.com"}}
        />
        </SectionErrorBoundary>
      </div>
  );
}
