// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTwoColumn from '@/components/sections/faq/FaqTwoColumn';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTwoColumn
          tag="Common Questions"
          title="Helpful Answers"
          description="Information about our store and services."
          items={[
            {
              question: "Where are you located?",          answer: "Via G. Matteotti, 49, 43017 San Secondo Parmense PR."},
            {
              question: "What are your opening hours?",          answer: "We are open daily. Please call 351 261 7506 for specific daily updates."},
            {
              question: "Do you sell international goods?",          answer: "Yes, we specialize in authentic Indian and exotic world cuisines."},
            {
              question: "Do you offer wholesale?",          answer: "Please visit us in-store to discuss your specific needs."},
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
