// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesBentoGrid from '@/components/sections/features/FeaturesBentoGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesBentoGrid
          tag="What We Offer"
          title="Quality Ingredients Daily"
          description="From daily staples to hard-to-find exotic spices, we provide everything needed for authentic home cooking."
          features={[
            {
              title: "Premium Basmati",          description: "High-quality, long-grain basmati rice sourced for perfect fragrance.",          imageSrc: "http://img.b2bpic.net/free-photo/top-view-plain-boiled-rice-with-different-spices_140725-151170.jpg"},
            {
              title: "Authentic Spices",          description: "Huge selection of aromatic spices, powders, and traditional blends.",          imageSrc: "http://img.b2bpic.net/free-photo/side-close-up-view-spices-table-spices-bowls-tree-branches-with-cones-christmas-tree-toys_140725-117315.jpg"},
            {
              title: "Fresh Essentials",          description: "Healthy cooking staples like coconut milk, oils, and lentils.",          imageSrc: "http://img.b2bpic.net/free-photo/organic-market-customer-checks-sauces_482257-76705.jpg"},
            {
              title: "Artisanal Finds",          description: "Curated selection of hard-to-find ethnic cooking ingredients.",          imageSrc: "http://img.b2bpic.net/free-photo/photo-vegetables-supermarket-photo-your-advertising_185193-110549.jpg"},
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
