// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardCarousel from '@/components/sections/hero/HeroBillboardCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardCarousel
          tag="Welcome to Sony KMB Market"
          title="Authentic Exotic Flavors in San Secondo"
          description="Discover a curated selection of authentic Indian spices, basmati rice, and exotic ingredients. Bringing the world's cuisine to your kitchen."
          primaryButton={{
            text: "Visit Us",        href: "#contact"}}
          secondaryButton={{
            text: "Explore Products",        href: "#products"}}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-street-market-sunset_23-2151530005.jpg"},
            {
              imageSrc: "http://img.b2bpic.net/free-photo/woman-supermarket-beautiful-young-woman-shopping-supermarket-buying-fresh-organic-vegetables_169016-3365.jpg"},
            {
              imageSrc: "http://img.b2bpic.net/free-photo/closeup-dried-spices-tea-backgroundin-grand-bazaar_181624-61326.jpg"},
            {
              imageSrc: "http://img.b2bpic.net/free-photo/client-shopping-local-retailer_23-2149349422.jpg"},
            {
              imageSrc: "http://img.b2bpic.net/free-photo/salad-bar-with-various-fresh-vegetables-supermarket_627829-7282.jpg"},
            {
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-indian-man-bazaar_23-2150913312.jpg"},
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
