// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
          tag="By The Numbers"
          title="Serving Our Community"
          description="Our commitment to quality and variety grows daily."
          metrics={[
            {
              value: "500+",          description: "Unique Products"},
            {
              value: "5.0",          description: "Customer Rating"},
            {
              value: "100%",          description: "Customer Satisfaction"},
            {
              value: "10+",          description: "Years of Tradition"},
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
