// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "products" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProductsSection(): React.JSX.Element {
  return (
    <div id="products" data-section="products">
        <SectionErrorBoundary name="products">
              <FeaturesImageBento
          tag="Our Catalog"
          title="Everything You Need"
          description="A diverse variety of culinary products for every kitchen."
          items={[
            {
              title: "Basmati Rice",          description: "Premium grains",          imageSrc: "http://img.b2bpic.net/free-photo/front-view-vegetable-composition-with-seasonings-white-background-color-photo-healthy-life-salad-meal-ripe-vegetable_140725-139564.jpg"},
            {
              title: "Exotic Spices",          description: "Aromatic varieties",          imageSrc: "http://img.b2bpic.net/free-photo/local-turkish-delices-tea-grand-bazar-market_1268-20173.jpg"},
            {
              title: "Coconut Milk",          description: "Pure goodness",          imageSrc: "http://img.b2bpic.net/free-photo/woman-stylish-denim-overalls-coffee-shop_273609-4411.jpg"},
            {
              title: "Organic Dal",          description: "Authentic lentils",          imageSrc: "http://img.b2bpic.net/free-photo/delicious-lentils-beans-plates-marble-surface_114579-54567.jpg"},
            {
              title: "Pickles & Chutneys",          description: "Traditional flavors",          imageSrc: "http://img.b2bpic.net/free-photo/jars-pickled-vegetables-boiled-potatoes-plate-marinated-vegetables-blue-table_114579-14530.jpg"},
            {
              title: "Curry Pastes",          description: "Ready to use",          imageSrc: "http://img.b2bpic.net/free-photo/boiled-chicken-cut-into-pieces-white-dish-wooden-table_1150-23172.jpg"},
            {
              title: "Fresh Produce",          description: "Seasonal items",          imageSrc: "http://img.b2bpic.net/free-photo/all-kinds-healthy-vegetable-farmer-market_23-2148209759.jpg"},
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
