// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialRatingCards from '@/components/sections/testimonial/TestimonialRatingCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialRatingCards
          tag="Reviews"
          title="Loved By Our Customers"
          description="Hear what the local community has to say about our store."
          testimonials={[
            {
              name: "ShuB RamGarhia",          role: "Local",          quote: "Nice work!",          rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-adult-woman-talking-phone_23-2148660711.jpg"},
            {
              name: "Ombretta Corradi",          role: "Local Guide",          quote: "Exotic cuisine heaven. Small space, massive variety.",          rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/brunette-woman-with-paper-bag-full-healthy-food_23-2148173305.jpg"},
            {
              name: "Jonny Giacomelli",          role: "Local Guide",          quote: "Huge variety of choice.",          rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-young-man-holding-fresh-vegetables-fruits-grocery-paper-bag_23-2147855409.jpg"},
            {
              name: "Sarah Miller",          role: "Foodie",          quote: "Best spices in the province, so helpful!",          rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-women-shopping-together_23-2149151643.jpg"},
            {
              name: "David Rossi",          role: "Home Cook",          quote: "Always fresh, great selection of rice.",          rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/young-man-doing-contactless-payment-fries_329181-20763.jpg"},
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
